version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 50
  groups:
    rails-deps:
      applies-to: security-updates
      patterns:
        - "rails"
        - "actioncable"
        - "actionmailbox"
        - "actionmailer"
        - "actionpack"
        - "actiontext"
        - "actionview"
        - "activejob"
        - "activemodel"
        - "activerecord"
        - "activestorage"
        - "activesupport"
        - "railties"
  labels:
    - "dependencies"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 50
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 50
