language: ruby
addons:
  postgresql: "9.4"
  chrome: stable
cache: bundler
bundler_args: --without development
before_script:
- for i in config/*.example; do cp "$i" "${i/.example}"; done
- bundle exec rake db:setup
script:
- "bundle exec rake assets:precompile RAILS_ENV=test > /dev/null 2>&1"
- "bin/knapsack_pro_rspec"
env:
  global:
  - KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true
  - KNAPSACK_PRO_LOG_LEVEL=info
  - KNAPSACK_PRO_CI_NODE_TOTAL=5
  - CI_NODE_TOTAL=5
  matrix:
  - KNAPSACK_PRO_CI_NODE_INDEX=0 CI_NODE_INDEX=0
  - KNAPSACK_PRO_CI_NODE_INDEX=1 CI_NODE_INDEX=1
  - KNAPSACK_PRO_CI_NODE_INDEX=2 CI_NODE_INDEX=2
  - KNAPSACK_PRO_CI_NODE_INDEX=3 CI_NODE_INDEX=3
  - KNAPSACK_PRO_CI_NODE_INDEX=4 CI_NODE_INDEX=4
