default: &default
  adapter: <%= ENV["DATABASE_ADAPTER"] || "postgresql" %>
  encoding: unicode
  host: <%= ENV["DATABASE_HOST"] || "localhost" %>
  pool: 5
  username: <%= ENV["DATABASE_USER"] || "postgres" %>
  password: <%= ENV["DATABASE_PASS"] || "root" %>

development: &development
  <<: *default
  database: <%= ENV["DATABASE"] || "consul_civicas" %>_development

staging:
  <<: *default
  database: <%= ENV["DATABASE"] || "consul_civicas" %>_staging

preproduction:
  <<: *default
  database: <%= ENV["DATABASE"] || "consul_civicas" %>_preproduction

production:
  <<: *default
  database: <%= ENV["DATABASE"] || "consul_civicas" %>_production

test:
  <<: *default
  database: <%= ENV["DATABASE"] || "consul_civicas" %>_test
