name: Kanban management
on:
  pull_request_target:
    types: [opened, reopened]
env:
  MY_GITHUB_TOKEN: ${{ secrets.KANBAN_TOKEN }}

jobs:
  assign_one_project:
    name: Add new pull requests to the kanban
    if: github.repository_owner == 'javierm'
    runs-on: ubuntu-latest
    steps:
    - name: Assign new pull requests to the reviewing column
      uses: andrenarchy/assign-one-project-github-action
      if: github.event.pull_request.draft == false
      with:
        project: "https://github.com/users/javierm/projects/4"
        column_name: "Reviewing"
        position: "bottom"

    - name: Assign new draft pull requests to the doing column
      uses: andrenarchy/assign-one-project-github-action
      if: github.event.pull_request.draft == true
      with:
        project: "https://github.com/users/javierm/projects/4"
        column_name: "Doing"
